name: Deploy DuoDash to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Prepare Build Files
        run: |
          BUILD_PATH=$(find . -name "index.html" -not -path "*/node_modules/*" -not -path "./public/*" -not -path "./src/*" | head -n 1)
          
          if [ -z "$BUILD_PATH" ]; then
            echo "Erro: Nenhuma pasta com index.html foi gerada no build."
            exit 1
          fi
          
          TARGET_DIR=$(dirname "$BUILD_PATH")
          echo "Pasta do build encontrada em: $TARGET_DIR"
          
          touch "$TARGET_DIR/.nojekyll"
          cp "$TARGET_DIR/index.html" "$TARGET_DIR/404.html"
          echo "TARGET_DIR=$TARGET_DIR" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.TARGET_DIR }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
